server:
  port: 8082

spring:
  application:
    name: grademusic-service
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/grademusic"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: "classpath:db/postgresql/liquibase/changelog.xml"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate



grade-music:
  jwt:
    secret-key: "123451234512345123451234512345123451234512345123451234512345123451234512345"
  redis:
    url: "redis://localhost:6379"
    password: "passWd"
    cache-expiration: P1D
  last-fm:
    api-key: "ecacf91992fe0d233fb4d8e8c4f3a5a0"
    base-url: "http://ws.audioscrobbler.com/2.0/"
    connection:
      timeout:
        connect: PT20S
        read: PT20S

management:
  endpoints:
    web:
      exposure:
        include: "*"
